namespace WoWonder.NiceArt.Models
{
    public enum PhotoFilter
    {
        None,
        AutoFix,
        BlackWhite,
        Brightness,
        Contrast,
        CrossProcess,
        Documentary,
        DueTone,
        FillLight,
        FishEye,
        FlipVertical,
        FlipHorizontal,
        Grain,
        GrayScale,
        Lomoish,
        Negative,
        Posterize,
        Rotate,
        Saturate,
        Sepia,
        Sharpen,
        Temperature,
        Tint,
        Vignette,
    }
}